# Set theme
# remote_theme: daviddarnes/garth

# File excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Set plugins
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Site settings
url: https://cbclobato.github.io
baseurl: ""
title: "Carolina Lobato"
description: "This is my new page"
permalink: pretty
logo: "/assets/carolina-lobato.jpg"

# if you don't have any of social below, comment the line
# scholar: yoururlgoeshere
github: cbclobato
twitter: cbclobato
linkedin: carolina-lobato

# facebook: myfacebook
# instagram: myinstagram
# email: carolinabclobato @gmail.com

# Pagination
paginate: 5
paginate_path: research/page:num

# Collections
collections:
  posts:
    title: #Research
    output: true
    description: #"There isn't much going on here yet, but watch this space"
